import React from "react";
import { Briefcase, Users, ShieldCheck, CalendarClock, FileText, TrendingUp, Target, Sparkles } from "lucide-react";
import Logo from "@/components/Logo";
import MobileNavigation from "@/components/MobileNavigation";
import { Button } from "@/components/ui/button";
import { useUser } from "@/contexts/SupabaseUserContext";

const insightCards = [
  {
    title: "Policy Refresh Window",
    value: "30 days",
    description: "Recommended timeframe to roll out updated templates across the organisation.",
    icon: CalendarClock,
  },
  {
    title: "Pending Approvals",
    value: "12",
    description: "Contracts awaiting legal sign-off across regional teams.",
    icon: FileText,
  },
  {
    title: "Process Optimisation",
    value: "3 suggestions",
    description: "Automations identified for enterprise workflows.",
    icon: Sparkles,
  },
];

const enterprisePlaybook = [
  {
    title: "Template Governance",
    detail: "Maintain a single source of truth for NDA, DPA, and MSA templates. Track variance requests directly from this dashboard.",
  },
  {
    title: "Regional Compliance",
    detail: "View regulatory coverage by geography and push remediation tasks to local owners with one click.",
  },
  {
    title: "Stakeholder Briefings",
    detail: "Export board-ready summaries highlighting resolved risks, outstanding clauses, and renewal forecasts.",
  },
];

export default function EnterpriseDashboard() {
  const { user } = useUser();
  const organisationName = user?.company || "Enterprise Partner";
  const planName = user?.plan.name || "Enterprise Plan";

  const executiveSummary = {
    totalWorkspaces: 6,
    activeUsers: 184,
    contractsThisQuarter: 312,
    autoGenerated: 148,
  };

  const adoptionMetrics = [
    { label: "Active Legal Seats", value: "48", change: "+6 this month" },
    { label: "Business Users", value: "136", change: "+18 new invites" },
    { label: "Templates in Rotation", value: "24", change: "5 flagged for refresh" },
  ];

  const riskHeat = [
    { region: "EMEA", rating: "Low", focus: "GDPR refresh" },
    { region: "AMER", rating: "Medium", focus: "Data residency clauses" },
    { region: "APAC", rating: "High", focus: "Vendor onboarding controls" },
  ];

  return (
    <div className="min-h-screen bg-[#F9F8F8] flex flex-col">
      <div className="flex items-center justify-between px-8 lg:px-16 py-6 border-b border-[#E8DDDD] bg-white">
        <div className="flex items-center gap-6">
          <Logo size="xl" />
          <div className="hidden md:flex items-center gap-6 text-sm text-[#271D1D]">
            <a href="/dashboard" className="hover:text-[#9A7C7C] transition-colors">Dashboard</a>
            <a href="/enterprise-dashboard" className="text-[#9A7C7C] font-medium">Enterprise Admin</a>
            <a href="/user-solutions" className="hover:text-[#9A7C7C] transition-colors">Solutions</a>
            <a href="/user-team" className="hover:text-[#9A7C7C] transition-colors">Team</a>
          </div>
        </div>
        <div className="md:hidden">
          <MobileNavigation isLoggedIn userName={user?.name?.split(" ")[0]} />
        </div>
        <div className="hidden md:flex items-center gap-3">
          <div className="text-right">
            <p className="text-xs text-[#725A5A] uppercase tracking-wide">{planName}</p>
            <p className="text-sm font-medium text-[#271D1D]">{organisationName}</p>
          </div>
          <Button asChild variant="outline" className="border-[#9A7C7C] text-[#9A7C7C]">
            <a href="/user-solutions">View Solutions</a>
          </Button>
        </div>
      </div>

      <main className="flex-1 px-6 lg:px-16 py-10 space-y-10">
        <section className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
            <div>
              <p className="text-xs uppercase tracking-[0.2em] text-[#9A7C7C] mb-2">Enterprise Control Centre</p>
              <h1 className="text-3xl lg:text-4xl font-lora text-[#271D1D] mb-3">
                {organisationName} Overview
              </h1>
              <p className="text-sm text-[#725A5A] max-w-2xl">
                Monitor enterprise-wide contract velocity, adoption, and compliance posture. Site admins can deploy updated templates, assign remediation tasks, and deliver quarterly board updates from a single workspace.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4 text-center">
                <p className="text-xs uppercase tracking-widest text-[#725A5A]">Active Workspaces</p>
                <p className="text-2xl font-semibold text-[#271D1D]">{executiveSummary.totalWorkspaces}</p>
              </div>
              <div className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4 text-center">
                <p className="text-xs uppercase tracking-widest text-[#725A5A]">Contracts Reviewed (QTD)</p>
                <p className="text-2xl font-semibold text-[#271D1D]">{executiveSummary.contractsThisQuarter}</p>
              </div>
              <div className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4 text-center">
                <p className="text-xs uppercase tracking-widest text-[#725A5A]">Auto-generated Summaries</p>
                <p className="text-2xl font-semibold text-[#271D1D]">{executiveSummary.autoGenerated}</p>
              </div>
              <div className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4 text-center">
                <p className="text-xs uppercase tracking-widest text-[#725A5A]">Active Users</p>
                <p className="text-2xl font-semibold text-[#271D1D]">{executiveSummary.activeUsers}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="grid grid-cols-1 xl:grid-cols-[2fr_1.1fr] gap-6">
          <div className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm space-y-6">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-[#9A7C7C]/15 text-[#9A7C7C] flex items-center justify-center">
                <Users className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#271D1D]">Adoption Snapshot</h2>
                <p className="text-sm text-[#725A5A]">Track engagement across business units and legal teams.</p>
              </div>
            </div>
            <div className="grid sm:grid-cols-3 gap-4">
              {adoptionMetrics.map((metric) => (
                <div key={metric.label} className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4">
                  <p className="text-xs uppercase tracking-wide text-[#725A5A] mb-2">{metric.label}</p>
                  <p className="text-2xl font-semibold text-[#271D1D]">{metric.value}</p>
                  <p className="text-xs text-[#9A7C7C] mt-2">{metric.change}</p>
                </div>
              ))}
            </div>
            <div className="bg-[#FDF7F4] border border-[#F2D6C9] rounded-xl p-4">
              <p className="text-sm font-medium text-[#9A7C7C] mb-1">Workflow spotlight</p>
              <p className="text-sm text-[#725A5A]">
                Auto-approve low risk NDAs under €50k and route escalations straight to the enterprise panel. Configure rules and roll them out to subsidiaries in minutes.
              </p>
            </div>
          </div>

          <div className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm space-y-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-[#9A7C7C]/15 text-[#9A7C7C] flex items-center justify-center">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#271D1D]">Regional Risk Heatmap</h2>
                <p className="text-sm text-[#725A5A]">Focus remediation where the exposure is highest.</p>
              </div>
            </div>
            <div className="space-y-3">
              {riskHeat.map((item) => (
                <div key={item.region} className="flex items-center justify-between rounded-xl border border-[#E8DDDD] px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-[#271D1D]">{item.region}</p>
                    <p className="text-xs text-[#725A5A]">{item.focus}</p>
                  </div>
                  <span className="text-xs font-semibold uppercase tracking-wide px-3 py-1 rounded-full bg-[#9A7C7C]/10 text-[#9A7C7C]">
                    {item.rating}
                  </span>
                </div>
              ))}
            </div>
            <Button variant="outline" className="w-full border-[#9A7C7C] text-[#9A7C7C] hover:bg-[#9A7C7C] hover:text-white">
              Export remediation brief
            </Button>
          </div>
        </section>

        <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {insightCards.map((card) => (
            <div key={card.title} className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm flex items-start gap-4">
              <div className="h-12 w-12 rounded-full bg-[#9A7C7C]/15 text-[#9A7C7C] flex items-center justify-center">
                <card.icon className="w-6 h-6" />
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-[#725A5A]">{card.title}</p>
                <p className="text-2xl font-semibold text-[#271D1D] my-2">{card.value}</p>
                <p className="text-sm text-[#725A5A]">{card.description}</p>
              </div>
            </div>
          ))}
          <div className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-10 w-10 rounded-full bg-[#9A7C7C]/15 text-[#9A7C7C] flex items-center justify-center">
                <TrendingUp className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#271D1D]">Key Milestones</h2>
                <p className="text-sm text-[#725A5A]">Stay ahead of renewals and governance checkpoints.</p>
              </div>
            </div>
            <ul className="space-y-3 text-sm text-[#725A5A]">
              <li className="flex items-start gap-3">
                <Target className="w-4 h-4 mt-1 text-[#9A7C7C]" />
                <span>H1 policy refresh window kicks off in 12 days. Review updated AI usage guidelines before launch.</span>
              </li>
              <li className="flex items-start gap-3">
                <Target className="w-4 h-4 mt-1 text-[#9A7C7C]" />
                <span>Vendor onboarding SLA is outperforming target by 2.5 days. Broadcast success metrics to regional leads.</span>
              </li>
              <li className="flex items-start gap-3">
                <Target className="w-4 h-4 mt-1 text-[#9A7C7C]" />
                <span>Security addendum for AI partners nearing approval. Coordinate rollout to 18 subsidiaries.</span>
              </li>
            </ul>
          </div>
        </section>

        <section className="bg-white border border-[#E8DDDD] rounded-2xl p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-6">
            <div className="h-10 w-10 rounded-full bg-[#9A7C7C]/15 text-[#9A7C7C] flex items-center justify-center">
              <Briefcase className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-[#271D1D]">Enterprise Playbook</h2>
              <p className="text-sm text-[#725A5A]">Curated workflow guidance for your site admin team.</p>
            </div>
          </div>
          <div className="grid md:grid-cols-3 gap-4">
            {enterprisePlaybook.map((item) => (
              <div key={item.title} className="bg-[#F9F8F8] border border-[#E8DDDD] rounded-xl p-4">
                <p className="text-xs uppercase tracking-wide text-[#9A7C7C] mb-2">{item.title}</p>
                <p className="text-sm text-[#725A5A] leading-relaxed">{item.detail}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
